### PR TITLE
introduce the minimum sample control for on full load api

### PR DESCRIPTION
**Pull request by fayums**

### CODE REVIEW

**Comment by aroudaki** [comment]
I dont think we usually include a solution along with control samples. We can just have the control code

**Comment by aroudaki** [comment]
Should we add a Readme and indicating this is not a publicly supported feature? (please check with the PM)

**Review by JimDaly — CHANGES_REQUESTED** [review]
Please don't check in package-lock.json

**Comment by JimDaly** [comment]
This feature isn't ready for a sample to be added.

**Pull request closed without merging**
