### PR TITLE
Replacing PDF for markdown files

### PR DESCRIPTION
**Pull request by aminespinoza**
In the **Build tools** you have a zip folder and also three PDF files with a great Hands-on Lab. Those files show some images from older version of Power Platform Products. My suggestion here is to replace those PDF files for Markdown. 
By using markdown files, it will be easier to keep them updated and also it allow other contributors to modify them and not only the owners of the original PDF files.
My idea is to show you how the first document would look like with this approach and if you concur I will start working on the remaining two documents. This is the best source when dealing with Power Apps and DevOps and it deserves to be as updated as possible.
If you agree, you can reject this PR and let me know to keep on converting the remaining documents to update the repository in one single PR.
Thanks!!

### CODE REVIEW

**Review by mikkelsen2000 — CHANGES_REQUESTED** [review]
Would love to have it all in markdown - we did this with the GitHub actions lab and I'd be absolutely thrilled if you'd do the same on the Build Tools lab :-)

**Comment by aminespinoza** [comment]
Sure @mikkelsen2000 !!! Gonna work on that, what about closing this PR and create a new one for Build Tools Lab in order to skip a larger amount of files.

**Comment by phecke** [comment]
@aminespinoza Sure, go ahead and close this PR.

**Comment by aminespinoza** [comment]
Closed to favor another PR with all modules in markdown format.

**Pull request closed without merging**
