### PR TITLE
Update ValidateKeyVaultForCMK script to add more validation on key

### PR DESCRIPTION
**Pull request by sokashya**
The code in this PR:
- updates ValidateKeyVaultForCMK script to add detailed validation for Key Vault and key as required by Power Platform enterprise policy
- updates the documentation in ReadMe file as per the changes in ValidateKeyVaultForCMK script 
- updated the screenshot

### CODE REVIEW

**Comment by JimDaly** [comment]
@sericks007 &  @Mattp123 

Can you take a look and make sure this is integrated with the appropriate docs?
If you can't merge into this repo, let me know.

**Comment by sokashya** [comment]
@paulliew @JimDaly Can you please help in getting this PR merged.
This PR updates ValidateKeyVaultForCMK script to add detailed validation for Key Vault and key as required by Power Platform enterprise policy. This will enable customer to troubleshooting the exact configuration problem in the key vault when there is some failure in CM

**Review by phecke — APPROVED** [review]
Made minor change to README. Removed en-us from links.

**Comment by phecke** [comment]
@sokashya Please work with the assigned technical writer to make sure any Learn documentation related to the script changes are kept in sync.

**Pull request merged**
