### PR TITLE
Xrm.WebApi TypeScript Samples for Model Driven Apps

### PR DESCRIPTION
**Pull request by scottdurow**
This PR includes samples on how to use the Xrm.WebApi from inside a model-driven app using TypeScript.

See the [readme on how to build and run the samples](https://github.com/scottdurow/PowerApps-Samples/blob/model-driven-app-webapi/cds/webapi/ts-model-driven-app/HowToRunSamples.md)

### CODE REVIEW

**Comment by Nkrb** [comment]
@scottdurow Thanks for the sample. We will review it and let you know

**Comment by KumarVivek** [comment]
Sent this to the feature team for review.

cc: @sidhartg

**Comment by scottdurow** [comment]
Any feedback on this PR?

**Comment by JimDaly** [comment]
@scottdurow 
Finally closing this as we discussed.

**Pull request closed without merging**
