### PR TITLE
updated FormattingAPIControl to use the parameters

### PR DESCRIPTION
**Pull request by BetimBeja**
I think this example is a little more helpful when it is working properly 😸

### CODE REVIEW

**Comment by JimDaly** [comment]
@BetimBeja 
Thank you for your submission. 
Just need to get one of the devs to take a look.

**Comment by BetimBeja** [comment]
@JimDaly I have actually been working on "something" and was using your examples to write the tests 
see here:
https://github.com/albanian-xrm/ComponentFramework-Mock-Tests

**Comment by JimDaly** [comment]
@kaushikkaul 
Can you review this PR?

**Review by kaushikkaul — APPROVED** [review]

**Comment by JimDaly** [comment]
Thank you @kaushikkaul  & @BetimBeja

**Pull request merged**
